//! In-process TSF context provider for OpenViKey.

#![allow(clippy::inline_always, clippy::ref_as_ptr)] // generated by windows-core `implement`

use std::ffi::c_void;
use std::ptr;
use std::sync::Mutex;
use std::sync::atomic::{AtomicUsize, Ordering};

use windows::Win32::Foundation::{
    CLASS_E_CLASSNOTAVAILABLE, CLASS_E_NOAGGREGATION, E_POINTER, S_FALSE, S_OK,
};
use windows::Win32::System::Com::{IClassFactory, IClassFactory_Impl};
use windows::Win32::UI::TextServices::{
    ITfTextInputProcessor_Impl, ITfTextInputProcessorEx, ITfTextInputProcessorEx_Impl, ITfThreadMgr,
};
use windows::core::{ComObject, Error, GUID, HRESULT, IUnknown, Interface, Ref, implement};

pub mod registration;

/// COM class identifier for the OpenViKey read-only TSF service.
pub const CLSID_OPENVIKEY_TSF: GUID = GUID::from_u128(0x741b179e_bf99_4ea2_bddf_b14ad06e7a60);
/// Language-profile identifier for the read-only Vietnamese context service.
pub const GUID_OPENVIKEY_PROFILE: GUID = GUID::from_u128(0x4da5e768_2736_4c63_aa94_6399134889a7);

static SERVER_STATE: ServerState = ServerState::new();

/// Counts live COM objects and explicit server locks for `DllCanUnloadNow`.
pub struct ServerState {
    objects: AtomicUsize,
    locks: AtomicUsize,
}

impl ServerState {
    /// Empty server state.
    pub const fn new() -> Self {
        Self {
            objects: AtomicUsize::new(0),
            locks: AtomicUsize::new(0),
        }
    }

    /// Whether COM may unload the DLL.
    #[must_use]
    pub fn can_unload(&self) -> bool {
        self.objects.load(Ordering::SeqCst) == 0 && self.locks.load(Ordering::SeqCst) == 0
    }

    fn acquire_object(&self) -> ObjectGuard<'_> {
        self.objects.fetch_add(1, Ordering::SeqCst);
        ObjectGuard { state: self }
    }

    fn set_lock(&self, lock: bool) {
        if lock {
            self.locks.fetch_add(1, Ordering::SeqCst);
        } else {
            let _ = self
                .locks
                .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |count| {
                    count.checked_sub(1)
                });
        }
    }
}

struct ObjectGuard<'a> {
    state: &'a ServerState,
}

impl Drop for ObjectGuard<'_> {
    fn drop(&mut self) {
        self.state.objects.fetch_sub(1, Ordering::SeqCst);
    }
}

#[implement(IClassFactory)]
struct ClassFactory {
    _object: ObjectGuard<'static>,
}

impl ClassFactory {
    fn new() -> Self {
        Self {
            _object: SERVER_STATE.acquire_object(),
        }
    }
}

impl IClassFactory_Impl for ClassFactory_Impl {
    fn CreateInstance(
        &self,
        punkouter: Ref<IUnknown>,
        riid: *const GUID,
        ppvobject: *mut *mut c_void,
    ) -> windows::core::Result<()> {
        if !punkouter.is_null() {
            return Err(Error::from_hresult(CLASS_E_NOAGGREGATION));
        }
        if riid.is_null() || ppvobject.is_null() {
            return Err(Error::from_hresult(E_POINTER));
        }
        unsafe {
            *ppvobject = ptr::null_mut();
        }

        let processor: ITfTextInputProcessorEx =
            ComObject::new(TextService::new()).into_interface();
        let result = unsafe { processor.query(riid, ppvobject) };
        drop(processor);
        result.ok()
    }

    fn LockServer(&self, flock: windows::core::BOOL) -> windows::core::Result<()> {
        SERVER_STATE.set_lock(flock.as_bool());
        Ok(())
    }
}

#[implement(ITfTextInputProcessorEx)]
struct TextService {
    _object: ObjectGuard<'static>,
    thread_manager: Mutex<Option<ITfThreadMgr>>,
}

impl TextService {
    fn new() -> Self {
        Self {
            _object: SERVER_STATE.acquire_object(),
            thread_manager: Mutex::new(None),
        }
    }

    fn activate(&self, thread_manager: &Ref<ITfThreadMgr>) -> windows::core::Result<()> {
        let manager = thread_manager
            .cloned()
            .ok_or_else(|| Error::from_hresult(E_POINTER))?;
        let mut current = self
            .thread_manager
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))?;
        *current = Some(manager);
        Ok(())
    }
}

impl ITfTextInputProcessor_Impl for TextService_Impl {
    fn Activate(&self, ptim: Ref<ITfThreadMgr>, _tid: u32) -> windows::core::Result<()> {
        self.activate(&ptim)
    }

    fn Deactivate(&self) -> windows::core::Result<()> {
        let mut current = self
            .thread_manager
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))?;
        *current = None;
        Ok(())
    }
}

impl ITfTextInputProcessorEx_Impl for TextService_Impl {
    fn ActivateEx(
        &self,
        ptim: Ref<ITfThreadMgr>,
        _tid: u32,
        _dwflags: u32,
    ) -> windows::core::Result<()> {
        self.activate(&ptim)
    }
}

/// Return the OpenViKey TSF class factory to COM.
///
/// # Safety
///
/// `rclsid`, `riid`, and `ppv` must follow the `DllGetClassObject` COM ABI contract.
#[unsafe(no_mangle)]
pub unsafe extern "system" fn DllGetClassObject(
    rclsid: *const GUID,
    riid: *const GUID,
    ppv: *mut *mut c_void,
) -> HRESULT {
    if rclsid.is_null() || riid.is_null() || ppv.is_null() {
        return E_POINTER;
    }
    unsafe {
        *ppv = ptr::null_mut();
    }
    if unsafe { *rclsid } != CLSID_OPENVIKEY_TSF {
        return CLASS_E_CLASSNOTAVAILABLE;
    }

    let factory: IClassFactory = ComObject::new(ClassFactory::new()).into_interface();
    let result = unsafe { factory.query(riid, ppv) };
    drop(factory);
    result
}

/// Tell COM whether all OpenViKey TSF objects and server locks are gone.
#[unsafe(no_mangle)]
pub extern "system" fn DllCanUnloadNow() -> HRESULT {
    if SERVER_STATE.can_unload() {
        S_OK
    } else {
        S_FALSE
    }
}

impl Default for ServerState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use std::ffi::c_void;
    use std::ptr;

    use windows::Win32::Foundation::S_OK;
    use windows::Win32::System::Com::{
        CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED, CoCreateInstance, CoInitializeEx,
        CoUninitialize, IClassFactory,
    };
    use windows::Win32::UI::TextServices::{
        CLSID_TF_ThreadMgr, ITfTextInputProcessorEx, ITfThreadMgr,
    };
    use windows::core::{IUnknown, Interface};

    use super::{CLSID_OPENVIKEY_TSF, DllCanUnloadNow, DllGetClassObject, ServerState};

    #[test]
    fn live_object_prevents_dll_unload() {
        let state = ServerState::new();
        let _object = state.acquire_object();

        assert!(!state.can_unload());
    }

    #[test]
    fn releasing_last_object_allows_dll_unload() {
        let state = ServerState::new();
        {
            let _object = state.acquire_object();
            assert!(!state.can_unload());
        }

        assert!(state.can_unload());
    }

    #[test]
    fn class_factory_creates_and_activates_text_processor() {
        unsafe {
            CoInitializeEx(None, COINIT_APARTMENTTHREADED).ok().unwrap();
        }

        let mut raw_factory: *mut c_void = ptr::null_mut();
        let result = unsafe {
            DllGetClassObject(
                &CLSID_OPENVIKEY_TSF,
                &IClassFactory::IID,
                &raw mut raw_factory,
            )
        };
        assert_eq!(result, S_OK);
        assert_eq!(DllCanUnloadNow(), windows::Win32::Foundation::S_FALSE);

        let factory = unsafe { IClassFactory::from_raw(raw_factory) };
        let processor: ITfTextInputProcessorEx = unsafe {
            factory
                .CreateInstance::<_, ITfTextInputProcessorEx>(None::<&IUnknown>)
                .unwrap()
        };
        drop(factory);

        let thread_manager: ITfThreadMgr = unsafe {
            CoCreateInstance(&CLSID_TF_ThreadMgr, None::<&IUnknown>, CLSCTX_INPROC_SERVER).unwrap()
        };
        let client_id = unsafe { thread_manager.Activate().unwrap() };
        unsafe {
            processor.ActivateEx(&thread_manager, client_id, 0).unwrap();
            processor.Deactivate().unwrap();
            thread_manager.Deactivate().unwrap();
        }
        drop(thread_manager);
        drop(processor);

        assert_eq!(DllCanUnloadNow(), S_OK);
        unsafe {
            CoUninitialize();
        }
    }
}
