//! In-process TSF context provider for OpenViKey.

#![allow(clippy::inline_always, clippy::ref_as_ptr)] // generated by windows-core `implement`

use std::ffi::c_void;
use std::mem::ManuallyDrop;
use std::ptr;
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

use windows::Win32::Foundation::{
    CLASS_E_CLASSNOTAVAILABLE, CLASS_E_NOAGGREGATION, E_POINTER, HWND, S_FALSE, S_OK,
};
use windows::Win32::System::Com::{
    CLSCTX_INPROC_SERVER, CoCreateInstance, CoTaskMemFree, IClassFactory, IClassFactory_Impl,
};
use windows::Win32::System::Threading::{GetCurrentProcessId, GetCurrentThreadId};
use windows::Win32::System::Variant::{VARIANT, VT_I4, VT_UNKNOWN, VariantClear};
use windows::Win32::UI::Accessibility::{CUIAutomation, IUIAutomation};
use windows::Win32::UI::TextServices::{
    GUID_COMPARTMENT_KEYBOARD_DISABLED, GUID_PROP_INPUTSCOPE, ITfCompartmentMgr, ITfContext,
    ITfDocumentMgr, ITfEditRecord, ITfEditSession, ITfEditSession_Impl, ITfInputScope, ITfRange,
    ITfSource, ITfTextEditSink, ITfTextEditSink_Impl, ITfTextInputProcessor_Impl,
    ITfTextInputProcessorEx, ITfTextInputProcessorEx_Impl, ITfThreadMgr, ITfThreadMgrEventSink,
    ITfThreadMgrEventSink_Impl, InputScope, TF_AE_START, TF_ANCHOR_END, TF_ANCHOR_START,
    TF_DEFAULT_SELECTION, TF_ES_ASYNCDONTCARE, TF_ES_READ, TF_SELECTION,
};
use windows::Win32::UI::WindowsAndMessaging::{GA_ROOT, GetAncestor};
use windows::core::{ComObject, Error, GUID, HRESULT, IUnknown, Interface, Ref, implement};
use windows_core::ComObjectInterface;

use openvikey_win_context::{
    ContextState, ReadContextResult, classify_input_scopes, extract_previous_token,
};

mod publisher;
pub mod registration;

use publisher::{ContextPublisher, SnapshotEmitter};

/// COM class identifier for the OpenViKey read-only TSF service.
pub const CLSID_OPENVIKEY_TSF: GUID = GUID::from_u128(0x741b179e_bf99_4ea2_bddf_b14ad06e7a60);
/// Language-profile identifier for the read-only Vietnamese context service.
pub const GUID_OPENVIKEY_PROFILE: GUID = GUID::from_u128(0x4da5e768_2736_4c63_aa94_6399134889a7);

trait TsfReadBoundary {
    fn automation_password(&self) -> bool {
        false
    }

    fn keyboard_disabled(&self) -> bool {
        false
    }

    fn input_scopes(&self) -> windows::core::Result<Option<Vec<i32>>>;
    fn left_text(&self) -> windows::core::Result<String>;
    fn hwnd(&self) -> Option<u64>;
}

fn read_owned_context(boundary: &impl TsfReadBoundary) -> ReadContextResult {
    let hwnd = boundary.hwnd();
    if boundary.automation_password() || boundary.keyboard_disabled() {
        return ReadContextResult {
            state: ContextState::Sensitive,
            left_token_nfc: None,
            hwnd,
        };
    }
    let state = match boundary.input_scopes() {
        Ok(scopes) => classify_input_scopes(scopes.as_deref().unwrap_or_default()),
        Err(_) => {
            return ReadContextResult {
                state: ContextState::Unavailable,
                left_token_nfc: None,
                hwnd,
            };
        }
    };
    if state == ContextState::Sensitive {
        return ReadContextResult {
            state,
            left_token_nfc: None,
            hwnd,
        };
    }
    match boundary.left_text() {
        Ok(text) => ReadContextResult {
            state: ContextState::Normal,
            left_token_nfc: extract_previous_token(&text),
            hwnd,
        },
        Err(_) => ReadContextResult {
            state: ContextState::Unavailable,
            left_token_nfc: None,
            hwnd,
        },
    }
}

struct ComReadBoundary {
    context: ITfContext,
    range: ITfRange,
    edit_cookie: u32,
}

impl TsfReadBoundary for ComReadBoundary {
    fn automation_password(&self) -> bool {
        let automation: windows::core::Result<IUIAutomation> =
            unsafe { CoCreateInstance(&CUIAutomation, None::<&IUnknown>, CLSCTX_INPROC_SERVER) };
        automation
            .and_then(|automation| unsafe { automation.GetFocusedElement() })
            .and_then(|element| unsafe { element.CurrentIsPassword() })
            .is_ok_and(windows_core::BOOL::as_bool)
    }

    fn keyboard_disabled(&self) -> bool {
        let Ok(manager) = self.context.cast::<ITfCompartmentMgr>() else {
            return false;
        };
        let Ok(compartment) =
            (unsafe { manager.GetCompartment(&GUID_COMPARTMENT_KEYBOARD_DISABLED) })
        else {
            return false;
        };
        let Ok(mut value) = (unsafe { compartment.GetValue() }) else {
            return false;
        };
        let inner = unsafe { &*value.Anonymous.Anonymous };
        let disabled = inner.vt == VT_I4 && unsafe { inner.Anonymous.lVal } != 0;
        let _ = unsafe { VariantClear(&raw mut value) };
        disabled
    }

    fn input_scopes(&self) -> windows::core::Result<Option<Vec<i32>>> {
        let property = match unsafe { self.context.GetAppProperty(&GUID_PROP_INPUTSCOPE) } {
            Ok(property) => property,
            Err(error) if error.code() == windows::Win32::Foundation::E_FAIL => return Ok(None),
            Err(error) => return Err(error),
        };
        let mut value = match unsafe { property.GetValue(self.edit_cookie, &self.range) } {
            Ok(value) => value,
            Err(error) if error.code() == windows::Win32::Foundation::E_FAIL => return Ok(None),
            Err(error) => return Err(error),
        };
        let scope_result = input_scope_from_variant(&mut value);
        let clear_result = unsafe { VariantClear(&raw mut value) };
        let scope = scope_result?;
        clear_result?;
        let Some(scope) = scope else {
            return Ok(None);
        };
        scopes_from_input_scope(&scope).map(Some)
    }

    fn left_text(&self) -> windows::core::Result<String> {
        let range = unsafe { self.range.Clone()? };
        let mut shifted = 0_i32;
        unsafe {
            range.ShiftStart(self.edit_cookie, -128, &raw mut shifted, ptr::null())?;
        }
        let mut text = [0_u16; 128];
        let mut read = 0_u32;
        unsafe {
            range.GetText(self.edit_cookie, 0, &mut text, &raw mut read)?;
        }
        let read = usize::try_from(read).unwrap_or(text.len()).min(text.len());
        Ok(String::from_utf16_lossy(&text[..read]))
    }

    fn hwnd(&self) -> Option<u64> {
        let view = unsafe { self.context.GetActiveView().ok()? };
        let hwnd = unsafe { view.GetWnd().ok()? };
        top_level_hwnd(hwnd)
    }
}

fn top_level_hwnd(hwnd: HWND) -> Option<u64> {
    if hwnd.is_invalid() {
        return None;
    }
    let root = unsafe { GetAncestor(hwnd, GA_ROOT) };
    let selected = if root.is_invalid() { hwnd } else { root };
    let raw = selected.0 as usize;
    (raw != 0).then(|| u64::try_from(raw).unwrap_or(u64::MAX))
}

fn input_scope_from_variant(value: &mut VARIANT) -> windows::core::Result<Option<ITfInputScope>> {
    let inner = unsafe { &*value.Anonymous.Anonymous };
    if inner.vt != VT_UNKNOWN {
        return Ok(None);
    }
    let unknown = unsafe { (*inner.Anonymous.punkVal).clone() };
    unknown.map(|unknown| unknown.cast()).transpose()
}

fn scopes_from_input_scope(scope: &ITfInputScope) -> windows::core::Result<Vec<i32>> {
    let mut allocation = CoTaskMemInputScopes(ptr::null_mut());
    let mut count = 0_u32;
    unsafe {
        scope.GetInputScopes(&raw mut allocation.0, &raw mut count)?;
    }
    let count = usize::try_from(count).map_err(|_| Error::from_hresult(E_POINTER))?;
    if count > 64 || (count > 0 && allocation.0.is_null()) {
        return Err(Error::from_hresult(E_POINTER));
    }
    let scopes = if count == 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(allocation.0, count) }
            .iter()
            .map(|scope| scope.0)
            .collect()
    };
    Ok(scopes)
}

struct CoTaskMemInputScopes(*mut InputScope);

impl Drop for CoTaskMemInputScopes {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe {
                CoTaskMemFree(Some(self.0.cast()));
            }
        }
    }
}

#[implement(ITfEditSession)]
struct ReadEditSession {
    _object: ObjectGuard<'static>,
    context: ITfContext,
    result: Arc<Mutex<Option<ReadContextResult>>>,
    emitter: SnapshotEmitter,
    context_seq: u64,
}

impl ITfEditSession_Impl for ReadEditSession_Impl {
    fn DoEditSession(&self, ec: u32) -> windows::core::Result<()> {
        let result = read_context_at(&self.context, ec);
        *self
            .result
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))? = Some(result.clone());
        self.emitter.publish(self.context_seq, result);
        Ok(())
    }
}

fn read_context_at(context: &ITfContext, edit_cookie: u32) -> ReadContextResult {
    match selection_range(context, edit_cookie) {
        Ok(range) => read_owned_context(&ComReadBoundary {
            context: context.clone(),
            range,
            edit_cookie,
        }),
        Err(_) => ReadContextResult {
            state: ContextState::Unavailable,
            left_token_nfc: None,
            hwnd: active_view_hwnd(context),
        },
    }
}

fn selection_range(context: &ITfContext, edit_cookie: u32) -> windows::core::Result<ITfRange> {
    let mut selection = [TF_SELECTION::default()];
    let mut fetched = 0_u32;
    unsafe {
        context.GetSelection(
            edit_cookie,
            TF_DEFAULT_SELECTION,
            &mut selection,
            &raw mut fetched,
        )?;
    }
    if fetched != 1 {
        return Err(Error::from_hresult(E_POINTER));
    }
    let anchor = if selection[0].style.ase == TF_AE_START {
        TF_ANCHOR_START
    } else {
        TF_ANCHOR_END
    };
    let range = unsafe { ManuallyDrop::take(&mut selection[0].range) }
        .ok_or_else(|| Error::from_hresult(E_POINTER))?;
    unsafe {
        range.Collapse(edit_cookie, anchor)?;
    }
    Ok(range)
}

fn active_view_hwnd(context: &ITfContext) -> Option<u64> {
    let view = unsafe { context.GetActiveView().ok()? };
    let hwnd = unsafe { view.GetWnd().ok()? };
    top_level_hwnd(hwnd)
}

static SERVER_STATE: ServerState = ServerState::new();
static NEXT_INSTANCE_ID: AtomicU64 = AtomicU64::new(1);

/// Counts live COM objects and explicit server locks for `DllCanUnloadNow`.
pub struct ServerState {
    objects: AtomicUsize,
    locks: AtomicUsize,
    workers: AtomicUsize,
}

impl ServerState {
    /// Empty server state.
    pub const fn new() -> Self {
        Self {
            objects: AtomicUsize::new(0),
            locks: AtomicUsize::new(0),
            workers: AtomicUsize::new(0),
        }
    }

    /// Whether COM may unload the DLL.
    #[must_use]
    pub fn can_unload(&self) -> bool {
        self.objects.load(Ordering::SeqCst) == 0
            && self.locks.load(Ordering::SeqCst) == 0
            && self.workers.load(Ordering::SeqCst) == 0
    }

    fn acquire_object(&self) -> ObjectGuard<'_> {
        self.objects.fetch_add(1, Ordering::SeqCst);
        ObjectGuard { state: self }
    }

    fn set_lock(&self, lock: bool) {
        if lock {
            self.locks.fetch_add(1, Ordering::SeqCst);
        } else {
            let _ = self
                .locks
                .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |count| {
                    count.checked_sub(1)
                });
        }
    }

    fn acquire_worker(&self) -> WorkerGuard<'_> {
        self.workers.fetch_add(1, Ordering::SeqCst);
        WorkerGuard { state: self }
    }
}

struct WorkerGuard<'a> {
    state: &'a ServerState,
}

impl Drop for WorkerGuard<'_> {
    fn drop(&mut self) {
        self.state.workers.fetch_sub(1, Ordering::SeqCst);
    }
}

struct ObjectGuard<'a> {
    state: &'a ServerState,
}

impl Drop for ObjectGuard<'_> {
    fn drop(&mut self) {
        self.state.objects.fetch_sub(1, Ordering::SeqCst);
    }
}

#[implement(IClassFactory)]
struct ClassFactory {
    _object: ObjectGuard<'static>,
}

impl ClassFactory {
    fn new() -> Self {
        Self {
            _object: SERVER_STATE.acquire_object(),
        }
    }
}

impl IClassFactory_Impl for ClassFactory_Impl {
    fn CreateInstance(
        &self,
        punkouter: Ref<IUnknown>,
        riid: *const GUID,
        ppvobject: *mut *mut c_void,
    ) -> windows::core::Result<()> {
        if !punkouter.is_null() {
            return Err(Error::from_hresult(CLASS_E_NOAGGREGATION));
        }
        if riid.is_null() || ppvobject.is_null() {
            return Err(Error::from_hresult(E_POINTER));
        }
        unsafe {
            *ppvobject = ptr::null_mut();
        }

        let processor: ITfTextInputProcessorEx =
            ComObject::new(TextService::new()).into_interface();
        let result = unsafe { processor.query(riid, ppvobject) };
        drop(processor);
        result.ok()
    }

    fn LockServer(&self, flock: windows::core::BOOL) -> windows::core::Result<()> {
        SERVER_STATE.set_lock(flock.as_bool());
        Ok(())
    }
}

#[implement(ITfTextInputProcessorEx, ITfThreadMgrEventSink, ITfTextEditSink)]
struct TextService {
    _object: ObjectGuard<'static>,
    thread_manager: Mutex<Option<ITfThreadMgr>>,
    thread_sink: Mutex<Option<(ITfSource, u32)>>,
    context_sink: Mutex<Option<(ITfSource, u32)>>,
    client_id: Mutex<Option<u32>>,
    last_read: Arc<Mutex<Option<ReadContextResult>>>,
    publisher: Mutex<Option<ContextPublisher>>,
    context_seq: AtomicU64,
}

impl TextService {
    fn new() -> Self {
        Self {
            _object: SERVER_STATE.acquire_object(),
            thread_manager: Mutex::new(None),
            thread_sink: Mutex::new(None),
            context_sink: Mutex::new(None),
            client_id: Mutex::new(None),
            last_read: Arc::new(Mutex::new(None)),
            publisher: Mutex::new(None),
            context_seq: AtomicU64::new(0),
        }
    }
}

fn unadvise_context(service: &TextService_Impl) -> windows::core::Result<()> {
    let advised = service
        .context_sink
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))?
        .take();
    if let Some((source, cookie)) = advised {
        unsafe {
            source.UnadviseSink(cookie)?;
        }
    }
    Ok(())
}

fn advise_context(
    service: &TextService_Impl,
    context: &Ref<ITfContext>,
) -> windows::core::Result<()> {
    unadvise_context(service)?;
    let context = context
        .cloned()
        .ok_or_else(|| Error::from_hresult(E_POINTER))?;
    let source: ITfSource = context.cast()?;
    let sink = <TextService_Impl as ComObjectInterface<ITfTextEditSink>>::as_interface_ref(service)
        .to_owned();
    let sink_unknown: IUnknown = sink.cast()?;
    let cookie = unsafe { source.AdviseSink(&ITfTextEditSink::IID, &sink_unknown)? };
    *service
        .context_sink
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some((source, cookie));
    request_context_read(service, &Ref::from(&context))
}

fn publish_read_result(
    service: &TextService_Impl,
    result: ReadContextResult,
) -> windows::core::Result<()> {
    let emitter = service
        .publisher
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))?
        .as_ref()
        .ok_or_else(|| Error::from_hresult(E_POINTER))?
        .emitter();
    let context_seq = service.context_seq.fetch_add(1, Ordering::Relaxed) + 1;
    *service
        .last_read
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some(result.clone());
    emitter.publish(context_seq, result);
    Ok(())
}

fn activate_service(
    service: &TextService_Impl,
    thread_manager: &Ref<ITfThreadMgr>,
    client_id: u32,
) -> windows::core::Result<()> {
    let manager = thread_manager
        .cloned()
        .ok_or_else(|| Error::from_hresult(E_POINTER))?;
    let process_id = unsafe { GetCurrentProcessId() };
    let thread_id = unsafe { GetCurrentThreadId() };
    let counter = NEXT_INSTANCE_ID.fetch_add(1, Ordering::Relaxed).max(1);
    let instance_id =
        ((u64::from(process_id) << 32) ^ (u64::from(thread_id) << 16) ^ counter).max(1);
    let publisher = ContextPublisher::start(process_id, thread_id, instance_id)?;
    let source: ITfSource = manager.cast()?;
    let sink =
        <TextService_Impl as ComObjectInterface<ITfThreadMgrEventSink>>::as_interface_ref(service)
            .to_owned();
    let sink_unknown: IUnknown = sink.cast()?;
    let cookie = unsafe { source.AdviseSink(&ITfThreadMgrEventSink::IID, &sink_unknown)? };

    *service
        .thread_manager
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some(manager);
    *service
        .thread_sink
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some((source, cookie));
    *service
        .client_id
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some(client_id);
    *service
        .publisher
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some(publisher);
    Ok(())
}

fn request_context_read(
    service: &TextService_Impl,
    context: &Ref<ITfContext>,
) -> windows::core::Result<()> {
    let context = context
        .cloned()
        .ok_or_else(|| Error::from_hresult(E_POINTER))?;
    let client_id = service
        .client_id
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))?
        .ok_or_else(|| Error::from_hresult(E_POINTER))?;
    let emitter = service
        .publisher
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))?
        .as_ref()
        .ok_or_else(|| Error::from_hresult(E_POINTER))?
        .emitter();
    let context_seq = service.context_seq.fetch_add(1, Ordering::Relaxed) + 1;
    let pending = ReadContextResult {
        state: ContextState::Pending,
        left_token_nfc: None,
        hwnd: active_view_hwnd(&context),
    };
    *service
        .last_read
        .lock()
        .map_err(|_| Error::from_hresult(E_POINTER))? = Some(pending.clone());
    emitter.publish(context_seq, pending);
    let edit_session: ITfEditSession = ComObject::new(ReadEditSession {
        _object: SERVER_STATE.acquire_object(),
        context: context.clone(),
        result: Arc::clone(&service.last_read),
        emitter: emitter.clone(),
        context_seq,
    })
    .into_interface();
    let session_result = unsafe {
        context.RequestEditSession(client_id, &edit_session, TF_ES_READ | TF_ES_ASYNCDONTCARE)?
    };
    if session_result.is_err() {
        let unavailable = ReadContextResult {
            state: ContextState::Unavailable,
            left_token_nfc: None,
            hwnd: active_view_hwnd(&context),
        };
        *service
            .last_read
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))? = Some(unavailable.clone());
        emitter.publish(context_seq, unavailable);
    }
    Ok(())
}

impl ITfTextInputProcessor_Impl for TextService_Impl {
    fn Activate(&self, ptim: Ref<ITfThreadMgr>, tid: u32) -> windows::core::Result<()> {
        activate_service(self, &ptim, tid)
    }

    fn Deactivate(&self) -> windows::core::Result<()> {
        unadvise_context(self)?;
        if let Some((source, cookie)) = self
            .thread_sink
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))?
            .take()
        {
            unsafe {
                source.UnadviseSink(cookie)?;
            }
        }
        if let Some(mut publisher) = self
            .publisher
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))?
            .take()
        {
            publisher.stop();
        }
        let mut current = self
            .thread_manager
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))?;
        *current = None;
        *self
            .client_id
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))? = None;
        *self
            .last_read
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))? = None;
        Ok(())
    }
}

impl ITfTextInputProcessorEx_Impl for TextService_Impl {
    fn ActivateEx(
        &self,
        ptim: Ref<ITfThreadMgr>,
        tid: u32,
        _dwflags: u32,
    ) -> windows::core::Result<()> {
        activate_service(self, &ptim, tid)
    }
}

impl ITfThreadMgrEventSink_Impl for TextService_Impl {
    fn OnInitDocumentMgr(&self, _pdim: Ref<ITfDocumentMgr>) -> windows::core::Result<()> {
        Ok(())
    }

    fn OnUninitDocumentMgr(&self, _pdim: Ref<ITfDocumentMgr>) -> windows::core::Result<()> {
        Ok(())
    }

    fn OnSetFocus(
        &self,
        pdimfocus: Ref<ITfDocumentMgr>,
        _pdimprevfocus: Ref<ITfDocumentMgr>,
    ) -> windows::core::Result<()> {
        let document = pdimfocus
            .cloned()
            .ok_or_else(|| Error::from_hresult(E_POINTER))?;
        let context = unsafe { document.GetTop()? };
        advise_context(self, &Ref::from(&context))
    }

    fn OnPushContext(&self, pic: Ref<ITfContext>) -> windows::core::Result<()> {
        advise_context(self, &pic)
    }

    fn OnPopContext(&self, _pic: Ref<ITfContext>) -> windows::core::Result<()> {
        unadvise_context(self)?;
        let manager = self
            .thread_manager
            .lock()
            .map_err(|_| Error::from_hresult(E_POINTER))?
            .clone()
            .ok_or_else(|| Error::from_hresult(E_POINTER))?;
        let document = unsafe { manager.GetFocus()? };
        let context = unsafe { document.GetTop()? };
        advise_context(self, &Ref::from(&context))
    }
}

impl ITfTextEditSink_Impl for TextService_Impl {
    fn OnEndEdit(
        &self,
        pic: Ref<ITfContext>,
        ecreadonly: u32,
        _peditrecord: Ref<ITfEditRecord>,
    ) -> windows::core::Result<()> {
        let context = pic.cloned().ok_or_else(|| Error::from_hresult(E_POINTER))?;
        publish_read_result(self, read_context_at(&context, ecreadonly))
    }
}

/// Return the OpenViKey TSF class factory to COM.
///
/// # Safety
///
/// `rclsid`, `riid`, and `ppv` must follow the `DllGetClassObject` COM ABI contract.
#[unsafe(no_mangle)]
pub unsafe extern "system" fn DllGetClassObject(
    rclsid: *const GUID,
    riid: *const GUID,
    ppv: *mut *mut c_void,
) -> HRESULT {
    if rclsid.is_null() || riid.is_null() || ppv.is_null() {
        return E_POINTER;
    }
    unsafe {
        *ppv = ptr::null_mut();
    }
    if unsafe { *rclsid } != CLSID_OPENVIKEY_TSF {
        return CLASS_E_CLASSNOTAVAILABLE;
    }

    let factory: IClassFactory = ComObject::new(ClassFactory::new()).into_interface();
    let result = unsafe { factory.query(riid, ppv) };
    drop(factory);
    result
}

/// Tell COM whether all OpenViKey TSF objects and server locks are gone.
#[unsafe(no_mangle)]
pub extern "system" fn DllCanUnloadNow() -> HRESULT {
    if SERVER_STATE.can_unload() {
        S_OK
    } else {
        S_FALSE
    }
}

impl Default for ServerState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use std::cell::Cell;
    use std::ffi::c_void;
    use std::ptr;
    use std::sync::{Arc, Mutex};
    use std::time::{Duration, Instant};

    use openvikey_win::context_bridge::ContextBridgeServer;
    use openvikey_win::focus::FocusCache;
    use openvikey_win::host::ContextProjectionSlot;
    use openvikey_win_context::{ContextProjection, ContextState, ReadContextResult};
    use windows::Win32::Foundation::S_OK;
    use windows::Win32::System::Com::{
        CLSCTX_INPROC_SERVER, COINIT_APARTMENTTHREADED, CoCreateInstance, CoInitializeEx,
        CoUninitialize, IClassFactory,
    };
    use windows::Win32::System::Threading::{GetCurrentProcessId, GetCurrentThreadId};
    use windows::Win32::UI::TextServices::{
        CLSID_TF_ThreadMgr, ITfTextInputProcessorEx, ITfThreadMgr,
    };
    use windows::core::{IUnknown, Interface};

    use super::{CLSID_OPENVIKEY_TSF, DllCanUnloadNow, DllGetClassObject, ServerState};

    static SERVER_TEST_LOCK: Mutex<()> = Mutex::new(());

    struct CountingReadBoundary {
        automation_password: bool,
        keyboard_disabled: bool,
        scopes: Vec<i32>,
        scope_reads: Cell<u32>,
        text_reads: Cell<u32>,
    }

    impl super::TsfReadBoundary for CountingReadBoundary {
        fn automation_password(&self) -> bool {
            self.automation_password
        }

        fn keyboard_disabled(&self) -> bool {
            self.keyboard_disabled
        }

        fn input_scopes(&self) -> windows::core::Result<Option<Vec<i32>>> {
            self.scope_reads.set(self.scope_reads.get() + 1);
            Ok(Some(self.scopes.clone()))
        }

        fn left_text(&self) -> windows::core::Result<String> {
            self.text_reads.set(self.text_reads.get() + 1);
            Ok("xin chào".to_owned())
        }

        fn hwnd(&self) -> Option<u64> {
            Some(42)
        }
    }

    struct MissingScopeBoundary;

    impl super::TsfReadBoundary for MissingScopeBoundary {
        fn input_scopes(&self) -> windows::core::Result<Option<Vec<i32>>> {
            Ok(None)
        }

        fn left_text(&self) -> windows::core::Result<String> {
            Ok("xin chào".to_owned())
        }

        fn hwnd(&self) -> Option<u64> {
            Some(42)
        }
    }

    #[test]
    fn missing_input_scope_is_normal_and_reads_left_context() {
        let result = super::read_owned_context(&MissingScopeBoundary);

        assert_eq!(result.state, ContextState::Normal);
        assert_eq!(result.left_token_nfc.as_deref(), Some("chào"));
    }

    #[test]
    fn automation_password_returns_sensitive_before_scope_or_text_read() {
        let boundary = CountingReadBoundary {
            automation_password: true,
            keyboard_disabled: false,
            scopes: Vec::new(),
            scope_reads: Cell::new(0),
            text_reads: Cell::new(0),
        };

        let result = super::read_owned_context(&boundary);

        assert_eq!(result.state, ContextState::Sensitive);
        assert_eq!(result.left_token_nfc, None);
        assert_eq!(boundary.scope_reads.get(), 0);
        assert_eq!(boundary.text_reads.get(), 0);
    }

    #[test]
    fn keyboard_disabled_returns_sensitive_before_scope_or_text_read() {
        let boundary = CountingReadBoundary {
            automation_password: false,
            keyboard_disabled: true,
            scopes: Vec::new(),
            scope_reads: Cell::new(0),
            text_reads: Cell::new(0),
        };

        let result = super::read_owned_context(&boundary);

        assert_eq!(result.state, ContextState::Sensitive);
        assert_eq!(result.left_token_nfc, None);
        assert_eq!(boundary.scope_reads.get(), 0);
        assert_eq!(boundary.text_reads.get(), 0);
    }

    #[test]
    fn sensitive_scope_returns_before_any_surrounding_text_read() {
        let boundary = CountingReadBoundary {
            automation_password: false,
            keyboard_disabled: false,
            scopes: vec![31],
            scope_reads: Cell::new(0),
            text_reads: Cell::new(0),
        };

        let result = super::read_owned_context(&boundary);

        assert_eq!(result.state, openvikey_win_context::ContextState::Sensitive);
        assert_eq!(result.left_token_nfc, None);
        assert_eq!(result.hwnd, Some(42));
        assert_eq!(boundary.text_reads.get(), 0);
    }

    #[test]
    fn publisher_connects_replaces_latest_and_stops_bounded() {
        let _server_test = SERVER_TEST_LOCK.lock().unwrap();
        let process_id = unsafe { GetCurrentProcessId() };
        let thread_id = unsafe { GetCurrentThreadId() };
        let pipe_name = format!(r"\\.\pipe\OpenViKey.Publisher.test.{process_id}.{thread_id}");
        let focus = Arc::new(FocusCache::new());
        focus.set_with_identity(42, "test.exe", process_id, thread_id);
        let projection = Arc::new(ContextProjectionSlot::new());
        let server =
            ContextBridgeServer::start_named(&pipe_name, focus, Arc::clone(&projection)).unwrap();
        let mut publisher =
            super::publisher::ContextPublisher::start_named(&pipe_name, process_id, thread_id, 99)
                .unwrap();
        wait_for_projection(&projection, |value| value == ContextProjection::Pending);

        publisher.emitter().publish(
            1,
            ReadContextResult {
                state: ContextState::Normal,
                left_token_nfc: Some("chào".to_owned()),
                hwnd: Some(42),
            },
        );
        wait_for_projection(&projection, |value| {
            matches!(value, ContextProjection::Normal { .. })
        });

        let started = Instant::now();
        publisher.stop();
        assert!(started.elapsed() < Duration::from_secs(1));
        drop(server);
    }

    fn wait_for_projection(
        slot: &ContextProjectionSlot,
        predicate: impl Fn(ContextProjection) -> bool,
    ) {
        let deadline = Instant::now() + Duration::from_secs(2);
        loop {
            if let Some(value) = slot.try_projection()
                && predicate(value)
            {
                return;
            }
            assert!(Instant::now() < deadline, "projection did not arrive");
            std::thread::sleep(Duration::from_millis(10));
        }
    }

    #[test]
    fn live_object_prevents_dll_unload() {
        let state = ServerState::new();
        let _object = state.acquire_object();

        assert!(!state.can_unload());
    }

    #[test]
    fn releasing_last_object_allows_dll_unload() {
        let state = ServerState::new();
        {
            let _object = state.acquire_object();
            assert!(!state.can_unload());
        }

        assert!(state.can_unload());
    }

    #[test]
    fn class_factory_creates_and_activates_text_processor() {
        let _server_test = SERVER_TEST_LOCK.lock().unwrap();
        unsafe {
            CoInitializeEx(None, COINIT_APARTMENTTHREADED).ok().unwrap();
        }

        let mut raw_factory: *mut c_void = ptr::null_mut();
        let result = unsafe {
            DllGetClassObject(
                &CLSID_OPENVIKEY_TSF,
                &IClassFactory::IID,
                &raw mut raw_factory,
            )
        };
        assert_eq!(result, S_OK);
        assert_eq!(DllCanUnloadNow(), windows::Win32::Foundation::S_FALSE);

        let factory = unsafe { IClassFactory::from_raw(raw_factory) };
        let processor: ITfTextInputProcessorEx = unsafe {
            factory
                .CreateInstance::<_, ITfTextInputProcessorEx>(None::<&IUnknown>)
                .unwrap()
        };
        drop(factory);

        let thread_manager: ITfThreadMgr = unsafe {
            CoCreateInstance(&CLSID_TF_ThreadMgr, None::<&IUnknown>, CLSCTX_INPROC_SERVER).unwrap()
        };
        let client_id = unsafe { thread_manager.Activate().unwrap() };
        unsafe {
            processor.ActivateEx(&thread_manager, client_id, 0).unwrap();
            processor.Deactivate().unwrap();
            thread_manager.Deactivate().unwrap();
        }
        drop(thread_manager);
        drop(processor);

        assert_eq!(DllCanUnloadNow(), S_OK);
        unsafe {
            CoUninitialize();
        }
    }

    #[test]
    #[ignore = "requires the development TSF server to be registered"]
    fn registered_com_server_activates_text_processor() {
        let _server_test = SERVER_TEST_LOCK.lock().unwrap();
        unsafe {
            CoInitializeEx(None, COINIT_APARTMENTTHREADED).ok().unwrap();
        }
        let processor: ITfTextInputProcessorEx = unsafe {
            CoCreateInstance(
                &CLSID_OPENVIKEY_TSF,
                None::<&IUnknown>,
                CLSCTX_INPROC_SERVER,
            )
            .unwrap()
        };
        let thread_manager: ITfThreadMgr = unsafe {
            CoCreateInstance(&CLSID_TF_ThreadMgr, None::<&IUnknown>, CLSCTX_INPROC_SERVER).unwrap()
        };
        let client_id = unsafe { thread_manager.Activate().unwrap() };
        unsafe {
            processor.ActivateEx(&thread_manager, client_id, 0).unwrap();
            processor.Deactivate().unwrap();
            thread_manager.Deactivate().unwrap();
        }
        drop(thread_manager);
        drop(processor);
        unsafe {
            CoUninitialize();
        }
    }
}
