//! Encrypted-payload capture log and deterministic reducer replay.

use crate::session::{LabSession, SessionCursors};
use openvikey_core::engine::EngineConfig;
use openvikey_core::lexicon::Lexicon;
use openvikey_core::model::{AdaptiveModel, ModelError};
use openvikey_core::store::file::FileModelStore;
use openvikey_core::store::passphrase::PassphraseProvider;
use openvikey_core::store::{StoreError, envelope};
use openvikey_core::types::InputEvent;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Component, Path, PathBuf};
use thiserror::Error;

pub const CAPTURE_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptureHeader {
    pub v: u32,
    pub next_seq: u64,
    pub next_edit_id: u64,
    #[serde(default)]
    pub last_at_ms: i64,
    #[serde(default)]
    pub model_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CaptureRecord {
    Input { event: InputEvent },
    AcceptTop { seq: u64, at_ms: i64 },
    RejectTop { seq: u64, at_ms: i64 },
    UndoLast { seq: u64, at_ms: i64 },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptureLog {
    pub header: CaptureHeader,
    pub records: Vec<CaptureRecord>,
}

impl CaptureLog {
    pub fn to_payload(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }

    pub fn from_payload(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }

    pub fn validate(&self) -> Result<(), SessionStoreError> {
        if self.header.v != CAPTURE_VERSION {
            return Err(SessionStoreError::UnsupportedVersion);
        }
        let max_seq = self.records.iter().map(record_seq).max();
        if let Some(max_seq) = max_seq
            && self.header.next_seq <= max_seq
        {
            return Err(SessionStoreError::CursorBehindLog);
        }
        Ok(())
    }
}

fn record_seq(record: &CaptureRecord) -> u64 {
    match record {
        CaptureRecord::Input { event } => event.seq,
        CaptureRecord::AcceptTop { seq, .. }
        | CaptureRecord::RejectTop { seq, .. }
        | CaptureRecord::UndoLast { seq, .. } => *seq,
    }
}

pub fn ensure_distinct_store_paths(
    model_path: &Path,
    capture_path: &Path,
) -> Result<(), SessionStoreError> {
    if store_paths_equal(model_path, capture_path) {
        return Err(SessionStoreError::SameStorePath);
    }
    Ok(())
}

fn store_paths_equal(left: &Path, right: &Path) -> bool {
    match (normalize_store_path(left), normalize_store_path(right)) {
        (Some(left), Some(right)) => platform_path_eq(&left, &right),
        _ => left == right,
    }
}

fn normalize_store_path(path: &Path) -> Option<PathBuf> {
    let absolute = std::path::absolute(path).ok()?;
    Some(lexical_normalize(&absolute))
}

fn lexical_normalize(path: &Path) -> PathBuf {
    let mut components = Vec::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                if matches!(components.last(), Some(Component::Normal(_))) {
                    components.pop();
                } else {
                    components.push(component);
                }
            }
            other => components.push(other),
        }
    }
    components.iter().collect()
}

fn platform_path_eq(left: &Path, right: &Path) -> bool {
    if left == right {
        return true;
    }
    #[cfg(windows)]
    {
        left.as_os_str().eq_ignore_ascii_case(right.as_os_str())
    }
    #[cfg(not(windows))]
    {
        false
    }
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

/// Replays command records through a fresh reducer. Capture is disabled so the
/// log is not duplicated. AutoSettled is regenerated by the live path.
#[must_use]
pub fn replay(engine_config: EngineConfig, lexicon: Lexicon, log: &CaptureLog) -> LabSession {
    replay_with_model(
        engine_config,
        lexicon,
        AdaptiveModel::default(),
        SessionCursors::default(),
        log,
    )
}

#[must_use]
pub fn replay_with_model(
    engine_config: EngineConfig,
    lexicon: Lexicon,
    model: AdaptiveModel,
    cursors: SessionCursors,
    log: &CaptureLog,
) -> LabSession {
    let mut session = LabSession::new_with_model(engine_config, lexicon, model, cursors);
    session.set_capturing(false);
    for record in &log.records {
        match record {
            CaptureRecord::Input { event } => {
                session.process_event(event);
            }
            CaptureRecord::AcceptTop { at_ms, .. } => {
                session.accept_top(*at_ms);
            }
            CaptureRecord::RejectTop { at_ms, .. } => {
                session.reject_top(*at_ms);
            }
            CaptureRecord::UndoLast { at_ms, .. } => {
                session.undo_last(*at_ms);
            }
        }
    }
    session
}

#[derive(Debug, Error)]
pub enum SessionStoreError {
    #[error("encrypted model is missing its capture log")]
    MissingCaptureLog,
    #[error("capture log exists but the encrypted model is missing")]
    OrphanCaptureLog,
    #[error("unsupported capture log version")]
    UnsupportedVersion,
    #[error("capture cursor is behind recorded sequence numbers")]
    CursorBehindLog,
    #[error("capture edit cursor is behind model auto-emission ids")]
    EditCursorBehindModel,
    #[error("model and capture paths must be distinct")]
    SameStorePath,
    #[error("encrypted model does not match its capture log")]
    InconsistentStore,
    #[error("invalid capture log payload: {0}")]
    CapturePayload(String),
    #[error(transparent)]
    Model(#[from] ModelError),
    #[error(transparent)]
    Store(#[from] StoreError),
}

/// Load encrypted model + capture log.
///
/// Both files missing → empty defaults. Capture without a model (including `.bak`)
/// is an error so the next save cannot overwrite an orphan log. If primaries
/// disagree, try `.bak` pairings for a hash-consistent pair.
pub fn load_personal_store(
    model_path: &Path,
    log_path: &Path,
    provider: &PassphraseProvider,
) -> Result<(AdaptiveModel, CaptureLog), SessionStoreError> {
    let model_store = FileModelStore::new(model_path);
    let log_store = FileModelStore::new(log_path);
    let model_backup_path = model_store.backup_path();
    let log_backup_path = log_store.backup_path();
    let model_present = model_path.exists() || model_backup_path.exists();
    let log_present = log_path.exists() || log_backup_path.exists();
    if !model_present && !log_present {
        return Ok((
            AdaptiveModel::default(),
            CaptureLog {
                header: CaptureHeader {
                    v: CAPTURE_VERSION,
                    next_seq: 1,
                    next_edit_id: 1,
                    last_at_ms: 0,
                    model_sha256: String::new(),
                },
                records: Vec::new(),
            },
        ));
    }
    if !model_present {
        return Err(SessionStoreError::OrphanCaptureLog);
    }
    if !log_present {
        return Err(SessionStoreError::MissingCaptureLog);
    }
    let model_primary = decrypt_store_file(model_path, provider)?;
    let log_primary = decrypt_store_file(log_path, provider)?;
    let model_backup = decrypt_store_file(&model_backup_path, provider)?;
    let log_backup = decrypt_store_file(&log_backup_path, provider)?;
    let pairs = [
        (model_primary.as_ref(), log_primary.as_ref()),
        (model_primary.as_ref(), log_backup.as_ref()),
        (model_backup.as_ref(), log_primary.as_ref()),
        (model_backup.as_ref(), log_backup.as_ref()),
    ];
    let mut saw_edit_cursor = false;
    for (model_bytes, log_bytes) in pairs {
        let (Some(model_bytes), Some(log_bytes)) = (model_bytes, log_bytes) else {
            continue;
        };
        match pair_if_consistent(model_bytes, log_bytes) {
            Ok(loaded) => return Ok(loaded),
            Err(SessionStoreError::EditCursorBehindModel) => saw_edit_cursor = true,
            Err(
                SessionStoreError::InconsistentStore
                | SessionStoreError::UnsupportedVersion
                | SessionStoreError::CursorBehindLog
                | SessionStoreError::CapturePayload(_)
                | SessionStoreError::Model(_),
            ) => {}
            Err(error) => return Err(error),
        }
    }
    if saw_edit_cursor {
        Err(SessionStoreError::EditCursorBehindModel)
    } else {
        Err(SessionStoreError::InconsistentStore)
    }
}

fn decrypt_store_file(
    path: &Path,
    provider: &PassphraseProvider,
) -> Result<Option<Vec<u8>>, SessionStoreError> {
    if !path.exists() {
        return Ok(None);
    }
    let bytes = fs::read(path).map_err(StoreError::from)?;
    match envelope::open(&bytes, provider) {
        Ok(payload) => Ok(Some(payload)),
        Err(StoreError::WrongPassphrase) => Err(StoreError::WrongPassphrase.into()),
        Err(_) => Ok(None),
    }
}

fn pair_if_consistent(
    model_bytes: &[u8],
    log_bytes: &[u8],
) -> Result<(AdaptiveModel, CaptureLog), SessionStoreError> {
    let model = AdaptiveModel::from_json_payload(model_bytes)?;
    let log = CaptureLog::from_payload(log_bytes)
        .map_err(|error| SessionStoreError::CapturePayload(error.to_string()))?;
    log.validate()?;
    if !log.header.model_sha256.is_empty() && log.header.model_sha256 != sha256_hex(model_bytes) {
        return Err(SessionStoreError::InconsistentStore);
    }
    let max_edit_id = max_edit_id_in_model_payload(model_bytes);
    if max_edit_id > 0 && log.header.next_edit_id <= max_edit_id {
        return Err(SessionStoreError::EditCursorBehindModel);
    }
    Ok((model, log))
}

fn max_edit_id_in_model_payload(payload: &[u8]) -> u64 {
    let Ok(value) = serde_json::from_slice::<serde_json::Value>(payload) else {
        return 0;
    };
    let Some(entries) = value.get("entries").and_then(serde_json::Value::as_array) else {
        return 0;
    };
    let mut max_id = 0;
    for entry in entries {
        if let Some(autos) = entry
            .get("recent_auto")
            .and_then(serde_json::Value::as_array)
        {
            for auto in autos {
                if let Some(id) = auto.get("edit_id").and_then(serde_json::Value::as_u64) {
                    max_id = max_id.max(id);
                }
            }
        }
        if let Some(ids) = entry
            .get("settled_auto_ids")
            .and_then(serde_json::Value::as_array)
        {
            for id in ids {
                if let Some(id) = id.as_u64() {
                    max_id = max_id.max(id);
                }
            }
        }
    }
    max_id
}
